import { RAECT_NATIVE_AUTH0_CLIENT_ID, RAECT_NATIVE_AUTH0_DOMAIN } from "@env";

export const AUTH0_CLIENT_ID = RAECT_NATIVE_AUTH0_CLIENT_ID || "";
export const AUTH0_DOMAIN = RAECT_NATIVE_AUTH0_DOMAIN || "";
