import {
  APP_THEME_KEY,
  NODE_ENV,
  REACT_NATIVE_API_URL_DEVELOPMENT,
  REACT_NATIVE_API_URL_PRODUCTION,
  REACT_NATIVE_SUPABASE_PUBLIC_KEY,
  REACT_NATIVE_SUPABASE_URL,
  SECURE_STORE_ACCESS_TOKEN_DEVELOP,
  SECURE_STORE_ACCESS_TOKEN_PRODUCTION,
  SECURE_STORE_PREVIOUS_AUTH_PROVIDER,
} from '@env';

export const THEME_KEY = APP_THEME_KEY || 'dark';

export const SUPABASE_URL = REACT_NATIVE_SUPABASE_URL || '';
export const SUPABASE_PUBLIC_KEY = REACT_NATIVE_SUPABASE_PUBLIC_KEY || '';

export const API_URL =
  NODE_ENV === 'development' ? REACT_NATIVE_API_URL_DEVELOPMENT : REACT_NATIVE_API_URL_PRODUCTION;

export const ACCESS_TOKEN_KEY =
  NODE_ENV === 'development'
    ? SECURE_STORE_ACCESS_TOKEN_DEVELOP
    : SECURE_STORE_ACCESS_TOKEN_PRODUCTION;
export const AUTH_PROVIDER_KEY = SECURE_STORE_PREVIOUS_AUTH_PROVIDER || '';
