import {
  REACT_NATIVE_PUBLIC_API_URL,
  REACT_NATIVE_SUPABASE_PUBLIC_KEY,
  REACT_NATIVE_SUPABASE_URL,
} from '@env';

export const API_URL = REACT_NATIVE_PUBLIC_API_URL || '';

export const SUPABASE_URL = REACT_NATIVE_SUPABASE_URL || '';
export const SUPABASE_PUBLIC_KEY = REACT_NATIVE_SUPABASE_PUBLIC_KEY || '';
