import { REACT_NATIVE_SUPABASE_PUBLIC_KEY, REACT_NATIVE_SUPABASE_URL } from "@env";

export const SUPABASE_URL = REACT_NATIVE_SUPABASE_URL || "";
export const SUPABASE_PUBLIC_KEY = REACT_NATIVE_SUPABASE_PUBLIC_KEY || "";
// export const SUPABASE_URL = process.env.REACT_NATIVE_SUPABASE_URL || "";
// export const SUPABASE_PUBLIC_KEY = process.env.REACT_NATIVE_SUPABASE_PUBLIC_KEY || "";
